version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mychatdb"

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: